<section class="o-hero o-container__hero">
  <div class="o-hero__container">
    <p class="o-hero__paragraph">Hi, I'm <span class="o-hero__name">Daiwei</span>. I build UIs and underlying architectures.</p>
    <p class="o-hero__paragraph o-hero__paragraph--secondary">I believe the best UIs are those users spend less time on but keep coming back to. Same thing for great archiectures, which make adding features and maintenance trivial things.</p>
  </div>
</section>
