<nav class="o-navbar">
  <div class="o-navbar__link-group">
    <a href="{{ blog }}" class="o-navbar__link">Blog</a>
    <a href="{{ github }}" class="o-navbar__link">Github</a>
    <a href="{{ twitter }}" class="o-navbar__link">Twitter</a>
  </div>
  <div class="o-navbar__link-group">
    <a href="#" class="o-navbar__link o-navbar__link--active" data-page="works">Works</a>
    <a href="#" class="o-navbar__link" data-page="profile">Profile</a>
  </div>
</nav>
